app:
  title: Backstage Example App
  baseUrl: http://localhost:7000

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  database:
    client: sqlite3
    connection: ':memory:'
  csp:
    connect-src: ["'self'", 'https:']

# See README.md in the proxy-backend plugin for information on the configuration format
proxy:
  '/circleci/api':
    target: https://circleci.com/api/v1.1
    headers:
      Circle-Token:
        $secret:
          env: CIRCLECI_AUTH_TOKEN

  '/jenkins/api':
    target: http://localhost:8080
    headers:
      Authorization:
        $secret:
          env: JENKINS_BASIC_AUTH_HEADER

  '/travisci/api':
    target: https://api.travis-ci.com
    changeOrigin: true
    headers:
      Authorization:
        $secret:
          env: TRAVISCI_AUTH_TOKEN
      travis-api-version: 3

organization:
  name: Spotify

techdocs:
  storageUrl: http://localhost:7000/api/techdocs/static/docs
  requestUrl: http://localhost:7000/api/techdocs
  generators:
    techdocs: 'docker'

sentry:
  organization: spotify

rollbar:
  organization: spotify
  accountToken:
    $secret:
      env: ROLLBAR_ACCOUNT_TOKEN

newrelic:
  api:
    baseUrl: 'https://api.newrelic.com/v2'
    key: NEW_RELIC_REST_API_KEY

lighthouse:
  baseUrl: http://localhost:3003

kubernetes:
  clusterLocatorMethod: 'configMultiTenant'
  clusters: []

integrations:
  github:
    - host: github.com
      token:
        $secret:
          env: GITHUB_PRIVATE_TOKEN
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token:
    #     $secret:
    #       env: GHE_PRIVATE_TOKEN
    ### Example for how to add your GitHub Enterprise instance using raw HTTP fetches (token is optional):
    # - host: ghe.example.net
    #   rawBaseUrl: https://ghe.example.net/raw
    #   token:
    #     $secret:
    #       env: GHE_PRIVATE_TOKEN
  gitlab:
    - host: gitlab.com
      token:
        $secret:
          env: GITLAB_PRIVATE_TOKEN
  bitbucket:
    - host: bitbucket.org
      username:
        $secret:
          env: BITBUCKET_USERNAME
      appPassword:
        $secret:
          env: BITBUCKET_APP_PASSWORD
  azure:
    - host: dev.azure.com
      token:
        $secret:
          env: AZURE_PRIVATE_TOKEN

catalog:
  rules:
    - allow: [Component, API, Group, User, Template, Location]

  processors:
    githubOrg:
      providers:
        - target: https://github.com
          token:
            $secret:
              env: GITHUB_PRIVATE_TOKEN
        #### Example for how to add your GitHub Enterprise instance using the API:
        # - target: https://ghe.example.net
        #   apiBaseUrl: https://ghe.example.net/api/v3
        #   token:
        #     $secret:
        #       env: GHE_PRIVATE_TOKEN

  locations:
    # Backstage example components
    - type: url
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/all-components.yaml
    # Example component for github-actions
    - type: url
      target: https://github.com/spotify/backstage/blob/master/plugins/github-actions/examples/sample.yaml
    # Example component for techdocs
    - type: url
      target: https://github.com/spotify/backstage/blob/master/plugins/techdocs-backend/examples/documented-component/documented-component.yaml
    # Backstage example APIs
    - type: url
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/all-apis.yaml
    # Backstage example templates
    - type: url
      target: https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/sample-templates/all-templates.yaml

scaffolder:
  github:
    token:
      $secret:
        env: GITHUB_ACCESS_TOKEN
    visibility: public # or 'internal' or 'private'
  gitlab:
    api:
      baseUrl: https://gitlab.com
      token:
        $secret:
          env: GITLAB_ACCESS_TOKEN
  azure:
    baseUrl: https://dev.azure.com/{your-organization}
    api:
      token:
        $secret:
          env: AZURE_PRIVATE_TOKEN

auth:
  providers:
    google:
      development:
        clientId:
          $secret:
            env: AUTH_GOOGLE_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_GOOGLE_CLIENT_SECRET
    github:
      development:
        clientId:
          $secret:
            env: AUTH_GITHUB_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_GITHUB_CLIENT_SECRET
        enterpriseInstanceUrl:
          $secret:
            env: AUTH_GITHUB_ENTERPRISE_INSTANCE_URL
    gitlab:
      development:
        clientId:
          $secret:
            env: AUTH_GITLAB_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_GITLAB_CLIENT_SECRET
        audience:
          $secret:
            env: GITLAB_BASE_URL
    saml:
      entryPoint: 'http://localhost:7001/'
      issuer: 'passport-saml'
    okta:
      development:
        clientId:
          $secret:
            env: AUTH_OKTA_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_OKTA_CLIENT_SECRET
        audience:
          $secret:
            env: AUTH_OKTA_AUDIENCE
    oauth2:
      development:
        clientId:
          $secret:
            env: AUTH_OAUTH2_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_OAUTH2_CLIENT_SECRET
        authorizationUrl:
          $secret:
            env: AUTH_OAUTH2_AUTH_URL
        tokenUrl:
          $secret:
            env: AUTH_OAUTH2_TOKEN_URL
    auth0:
      development:
        clientId:
          $secret:
            env: AUTH_AUTH0_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_AUTH0_CLIENT_SECRET
        domain:
          $secret:
            env: AUTH_AUTH0_DOMAIN
    microsoft:
      development:
        clientId:
          $secret:
            env: AUTH_MICROSOFT_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_MICROSOFT_CLIENT_SECRET
        tenantId:
          $secret:
            env: AUTH_MICROSOFT_TENANT_ID
costInsights:
  engineerCost: 200000
  products:
    computeEngine:
      name: Compute Engine
      icon: compute
    cloudDataflow:
      name: Cloud Dataflow
      icon: data
    cloudStorage:
      name: Cloud Storage
      icon: storage
    bigQuery:
      name: Big Query
      icon: search
  metrics:
    dailyCost:
      name: Your Company's Daily Cost
    DAU:
      name: Cost Per DAU
homepage:
  clocks:
    - label: UTC
      timzone: UTC
    - label: NYC
      timezone: 'America/New_York'
    - label: STO
      timezone: 'Europe/Stockholm'
    - label: TYO
      timezone: 'Asia/Tokyo'
